#!/usr/bin/env bash
# PRODUCTIZATION-4D — build the application bundle for the local appliance.
#
# Same source, same transactional engines, same Nitro fetch-handler artefact as
# the hosted deployment. The ONLY difference is configuration: the client is
# built against a sentinel origin which `stamp-ui.sh` rewrites to the real
# appliance origin at install time, so no customer address is ever baked in.
#
# PRODUCTIZATION-4F: the build must NOT inherit the developer's hosted
# configuration. A checked-in `.env` at the repository root (hosted project
# URL/keys) would otherwise be inlined into the appliance bundle, so we shadow
# it with a temporary `.env.local` (higher precedence, git-ignored) for the
# duration of the build and always restore the previous state.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

SENTINEL="${NOVA_ORIGIN_SENTINEL:-https://nova-appliance.invalid}"
ANON="${NOVA_LOCAL_ANON_KEY:-nova-local-anon}"

export VITE_NOVA_RUNTIME_MODE=local
export NOVA_RUNTIME_MODE=local
export VITE_SUPABASE_URL="$SENTINEL"
export VITE_SUPABASE_PUBLISHABLE_KEY="$ANON"
export VITE_SUPABASE_PROJECT_ID=nova-local
export SUPABASE_URL="$SENTINEL"
export SUPABASE_PUBLISHABLE_KEY="$ANON"
export SUPABASE_PROJECT_ID=nova-local

OVERRIDE="$NOVA_ROOT/.env.local"
BACKUP="$NOVA_ROOT/.env.local.nova-backup"
restore_env() {
  if [[ -f "$BACKUP" ]]; then mv -f "$BACKUP" "$OVERRIDE"; else rm -f "$OVERRIDE"; fi
}
[[ -f "$OVERRIDE" ]] && mv -f "$OVERRIDE" "$BACKUP"
trap restore_env EXIT
cat > "$OVERRIDE" <<ENVFILE
# Generated by local/scripts/build-ui.sh — removed automatically after the build.
VITE_SUPABASE_URL=$SENTINEL
VITE_SUPABASE_PUBLISHABLE_KEY=$ANON
VITE_SUPABASE_PROJECT_ID=nova-local
SUPABASE_URL=$SENTINEL
SUPABASE_PUBLISHABLE_KEY=$ANON
SUPABASE_PROJECT_ID=nova-local
VITE_NOVA_RUNTIME_MODE=local
ENVFILE

nova_log "Building NOVA Hospitality UI for the local appliance"
( cd "$NOVA_ROOT" && bun run build )

# The Vite/Nitro build emits `.output/{public,server}`, but the appliance
# runtime contract (gateway + verify-bundle.sh + tests) is `dist/client` and
# `dist/server/index.mjs`. Package the generated output into that contract
# rather than changing the consumer contract.
OUT="$NOVA_ROOT/.output"
if [[ -d "$OUT/public" && -f "$OUT/server/index.mjs" ]]; then
  nova_log "Packaging Nitro output into the appliance bundle contract (dist/)"
  rm -rf "$NOVA_ROOT/dist/client" "$NOVA_ROOT/dist/server"
  mkdir -p "$NOVA_ROOT/dist/client" "$NOVA_ROOT/dist/server"
  cp -R "$OUT/public/." "$NOVA_ROOT/dist/client/"
  cp -R "$OUT/server/." "$NOVA_ROOT/dist/server/"
elif [[ -d "$NOVA_ROOT/dist/client" && -f "$NOVA_ROOT/dist/server/index.mjs" ]]; then
  nova_log "Build already emitted the appliance bundle layout in dist/"
else
  echo "FATAL: application build completed but expected Nitro output was not found" >&2
  echo "       looked for: $OUT/public and $OUT/server/index.mjs" >&2
  echo "       (and no pre-existing $NOVA_ROOT/dist/client + dist/server/index.mjs)" >&2
  exit 1
fi

[[ -f "$NOVA_ROOT/dist/server/index.mjs" ]] || {
  echo "FATAL: dist/server/index.mjs missing after packaging — refusing to write a partial bundle" >&2
  exit 1
}
# Never ship environment files or key material inside the served bundle.
find "$NOVA_ROOT/dist/client" "$NOVA_ROOT/dist/server" \
  \( -name '.env' -o -name '.env.*' -o -name '*.pem' -o -name '*.key' \) -type f -delete 2>/dev/null || true

printf '{"built_at":"%s","origin_sentinel":"%s","runtime_mode":"local"}\n' \
  "$(date -u +%FT%TZ)" "$SENTINEL" > "$NOVA_ROOT/dist/.nova-local-build"
nova_log "UI bundle written to $NOVA_ROOT/dist (local build marker written)"
bash "$NOVA_LOCAL_DIR/scripts/verify-bundle.sh" "$NOVA_ROOT/dist"
