import { useState } from "react";
import { Menu, X, Sparkles } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { trackBookingClick } from "@/lib/analytics";
const links = [{ to: "/rooms", label: "Rooms" }, { to: "/book", label: "Availability" }] as const;
export function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-md">
    <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-6 lg:h-20 lg:px-10">
      <Link to="/rooms" aria-label="StayNas" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm font-semibold">S</span><span className="text-sm font-semibold tracking-[0.22em] uppercase">StayNas</span></Link>
      <nav className="hidden items-center gap-8 lg:flex">{links.map(l => <Link key={l.to} to={l.to} className="text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground transition-colors hover:text-foreground" activeProps={{className:"text-xs font-medium uppercase tracking-[0.2em] text-foreground"}}>{l.label}</Link>)}<Link to="/book" onClick={()=>trackBookingClick({buttonText:"Check Availability",location:"nav_desktop"})} className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-xs font-semibold uppercase tracking-[0.18em] text-primary-foreground shadow-sm transition hover:brightness-110">Check availability <span>→</span></Link></nav>
      <button aria-label="Open menu" onClick={()=>setOpen(true)} className="inline-flex h-11 w-11 items-center justify-center rounded-full border lg:hidden"><Menu className="h-5 w-5"/></button>
    </div>
    {open && <div className="fixed inset-0 z-50 bg-background lg:hidden"><div className="flex h-16 items-center justify-between border-b px-5"><Link to="/rooms" onClick={()=>setOpen(false)} className="text-sm font-semibold tracking-[0.22em] uppercase">StayNas</Link><button aria-label="Close menu" onClick={()=>setOpen(false)} className="inline-flex h-11 w-11 items-center justify-center rounded-full border"><X className="h-5 w-5"/></button></div><nav className="flex flex-col gap-2 px-6 py-10">{links.map(l=><Link key={l.to} to={l.to} onClick={()=>setOpen(false)} className="flex items-center justify-between border-b py-5 text-xl font-medium">{l.label}<span>→</span></Link>)}<Link to="/book" onClick={()=>{setOpen(false);trackBookingClick({buttonText:"Check Availability",location:"nav_mobile"})}} className="mt-8 inline-flex items-center justify-center gap-2 rounded-full bg-primary px-6 py-4 text-xs font-semibold uppercase tracking-[0.2em] text-primary-foreground">Check availability</Link><div className="mt-8 rounded-2xl border bg-muted/40 p-5"><div className="flex items-center gap-2 text-sm font-medium"><Sparkles className="h-4 w-4 text-primary"/> StayNas AI</div><p className="mt-2 text-sm leading-6 text-muted-foreground">Intelligent assistance for the guest journey.</p></div></nav></div>}
  </header>;
}