/**
 * Guest Arrival Intelligence — shared contracts (client-safe).
 * The briefing is advisory only: it never changes reservation, room or
 * guest state and is never shown to guests.
 */
import { z } from "zod";

export const arrivalBriefingSchema = z.object({
  bookingId: z.string().uuid(),
  /** Force a fresh generation instead of reusing the stored briefing. */
  refresh: z.boolean().optional().default(false),
});
export type ArrivalBriefingInput = z.infer<typeof arrivalBriefingSchema>;

export interface ArrivalBriefing {
  bookingId: string;
  summary: string;
  highlights: string[];
  attention: string[];
  /** "ai" when generated by the AI Gateway, "fallback" when derived locally. */
  source: "ai" | "fallback" | "cached";
  generatedAt: string;
  model: string | null;
}
