/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LodgeRouteImport } from './routes/lodge'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DiningLeisureRouteImport } from './routes/dining-leisure'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingFormRouteImport } from './routes/booking-form'
import { Route as BookRouteImport } from './routes/book'
import { Route as AmenitiesActivitiesRouteImport } from './routes/amenities-activities'
import { Route as AccommodationsRouteImport } from './routes/accommodations'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as RoomsStandardRiverRouteImport } from './routes/rooms.standard-river'
import { Route as RoomsRiverfrontDeluxeRouteImport } from './routes/rooms.riverfront-deluxe'
import { Route as RoomsFamilyRoomRouteImport } from './routes/rooms.family-room'
import { Route as JournalWhatTheRiverHasTaughtUsAboutTimeRouteImport } from './routes/journal.what-the-river-has-taught-us-about-time'
import { Route as JournalTheArchitectureOfDisappearingRouteImport } from './routes/journal.the-architecture-of-disappearing'
import { Route as JournalReadingTheSkyOverMountMeruRouteImport } from './routes/journal.reading-the-sky-over-mount-meru'
import { Route as JournalPerfectArushaStayForSafariTravelers2026RouteImport } from './routes/journal.perfect-arusha-stay-for-safari-travelers-2026'
import { Route as JournalLifeAlongTheNdurumaRiverRouteImport } from './routes/journal.life-along-the-nduruma-river'
import { Route as JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRouteImport } from './routes/journal.discovering-arusha-through-nature-and-authentic-hospitality'
import { Route as JournalBuildingWithTheCommunityRouteImport } from './routes/journal.building-with-the-community'
import { Route as JournalAMorningWithTheBeekeepersOfGombaRouteImport } from './routes/journal.a-morning-with-the-beekeepers-of-gomba'

const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LodgeRoute = LodgeRouteImport.update({
  id: '/lodge',
  path: '/lodge',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningLeisureRoute = DiningLeisureRouteImport.update({
  id: '/dining-leisure',
  path: '/dining-leisure',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFormRoute = BookingFormRouteImport.update({
  id: '/booking-form',
  path: '/booking-form',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesActivitiesRoute = AmenitiesActivitiesRouteImport.update({
  id: '/amenities-activities',
  path: '/amenities-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsRoute = AccommodationsRouteImport.update({
  id: '/accommodations',
  path: '/accommodations',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const RoomsStandardRiverRoute = RoomsStandardRiverRouteImport.update({
  id: '/standard-river',
  path: '/standard-river',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsRiverfrontDeluxeRoute = RoomsRiverfrontDeluxeRouteImport.update({
  id: '/riverfront-deluxe',
  path: '/riverfront-deluxe',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsFamilyRoomRoute = RoomsFamilyRoomRouteImport.update({
  id: '/family-room',
  path: '/family-room',
  getParentRoute: () => RoomsRoute,
} as any)
const JournalWhatTheRiverHasTaughtUsAboutTimeRoute =
  JournalWhatTheRiverHasTaughtUsAboutTimeRouteImport.update({
    id: '/what-the-river-has-taught-us-about-time',
    path: '/what-the-river-has-taught-us-about-time',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalTheArchitectureOfDisappearingRoute =
  JournalTheArchitectureOfDisappearingRouteImport.update({
    id: '/the-architecture-of-disappearing',
    path: '/the-architecture-of-disappearing',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalReadingTheSkyOverMountMeruRoute =
  JournalReadingTheSkyOverMountMeruRouteImport.update({
    id: '/reading-the-sky-over-mount-meru',
    path: '/reading-the-sky-over-mount-meru',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalPerfectArushaStayForSafariTravelers2026Route =
  JournalPerfectArushaStayForSafariTravelers2026RouteImport.update({
    id: '/perfect-arusha-stay-for-safari-travelers-2026',
    path: '/perfect-arusha-stay-for-safari-travelers-2026',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalLifeAlongTheNdurumaRiverRoute =
  JournalLifeAlongTheNdurumaRiverRouteImport.update({
    id: '/life-along-the-nduruma-river',
    path: '/life-along-the-nduruma-river',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute =
  JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRouteImport.update(
    {
      id: '/discovering-arusha-through-nature-and-authentic-hospitality',
      path: '/discovering-arusha-through-nature-and-authentic-hospitality',
      getParentRoute: () => JournalRoute,
    } as any,
  )
const JournalBuildingWithTheCommunityRoute =
  JournalBuildingWithTheCommunityRouteImport.update({
    id: '/building-with-the-community',
    path: '/building-with-the-community',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalAMorningWithTheBeekeepersOfGombaRoute =
  JournalAMorningWithTheBeekeepersOfGombaRouteImport.update({
    id: '/a-morning-with-the-beekeepers-of-gomba',
    path: '/a-morning-with-the-beekeepers-of-gomba',
    getParentRoute: () => JournalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accommodations': typeof AccommodationsRoute
  '/amenities-activities': typeof AmenitiesActivitiesRoute
  '/book': typeof BookRoute
  '/booking-form': typeof BookingFormRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/dining-leisure': typeof DiningLeisureRoute
  '/experiences': typeof ExperiencesRoute
  '/journal': typeof JournalRouteWithChildren
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/suites': typeof SuitesRoute
  '/terms': typeof TermsRoute
  '/vote': typeof VoteRoute
  '/journal/a-morning-with-the-beekeepers-of-gomba': typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  '/journal/building-with-the-community': typeof JournalBuildingWithTheCommunityRoute
  '/journal/discovering-arusha-through-nature-and-authentic-hospitality': typeof JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute
  '/journal/life-along-the-nduruma-river': typeof JournalLifeAlongTheNdurumaRiverRoute
  '/journal/perfect-arusha-stay-for-safari-travelers-2026': typeof JournalPerfectArushaStayForSafariTravelers2026Route
  '/journal/reading-the-sky-over-mount-meru': typeof JournalReadingTheSkyOverMountMeruRoute
  '/journal/the-architecture-of-disappearing': typeof JournalTheArchitectureOfDisappearingRoute
  '/journal/what-the-river-has-taught-us-about-time': typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  '/rooms/family-room': typeof RoomsFamilyRoomRoute
  '/rooms/riverfront-deluxe': typeof RoomsRiverfrontDeluxeRoute
  '/rooms/standard-river': typeof RoomsStandardRiverRoute
  '/journal/': typeof JournalIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accommodations': typeof AccommodationsRoute
  '/amenities-activities': typeof AmenitiesActivitiesRoute
  '/book': typeof BookRoute
  '/booking-form': typeof BookingFormRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/dining-leisure': typeof DiningLeisureRoute
  '/experiences': typeof ExperiencesRoute
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/suites': typeof SuitesRoute
  '/terms': typeof TermsRoute
  '/vote': typeof VoteRoute
  '/journal/a-morning-with-the-beekeepers-of-gomba': typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  '/journal/building-with-the-community': typeof JournalBuildingWithTheCommunityRoute
  '/journal/discovering-arusha-through-nature-and-authentic-hospitality': typeof JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute
  '/journal/life-along-the-nduruma-river': typeof JournalLifeAlongTheNdurumaRiverRoute
  '/journal/perfect-arusha-stay-for-safari-travelers-2026': typeof JournalPerfectArushaStayForSafariTravelers2026Route
  '/journal/reading-the-sky-over-mount-meru': typeof JournalReadingTheSkyOverMountMeruRoute
  '/journal/the-architecture-of-disappearing': typeof JournalTheArchitectureOfDisappearingRoute
  '/journal/what-the-river-has-taught-us-about-time': typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  '/rooms/family-room': typeof RoomsFamilyRoomRoute
  '/rooms/riverfront-deluxe': typeof RoomsRiverfrontDeluxeRoute
  '/rooms/standard-river': typeof RoomsStandardRiverRoute
  '/journal': typeof JournalIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accommodations': typeof AccommodationsRoute
  '/amenities-activities': typeof AmenitiesActivitiesRoute
  '/book': typeof BookRoute
  '/booking-form': typeof BookingFormRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/dining-leisure': typeof DiningLeisureRoute
  '/experiences': typeof ExperiencesRoute
  '/journal': typeof JournalRouteWithChildren
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/suites': typeof SuitesRoute
  '/terms': typeof TermsRoute
  '/vote': typeof VoteRoute
  '/journal/a-morning-with-the-beekeepers-of-gomba': typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  '/journal/building-with-the-community': typeof JournalBuildingWithTheCommunityRoute
  '/journal/discovering-arusha-through-nature-and-authentic-hospitality': typeof JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute
  '/journal/life-along-the-nduruma-river': typeof JournalLifeAlongTheNdurumaRiverRoute
  '/journal/perfect-arusha-stay-for-safari-travelers-2026': typeof JournalPerfectArushaStayForSafariTravelers2026Route
  '/journal/reading-the-sky-over-mount-meru': typeof JournalReadingTheSkyOverMountMeruRoute
  '/journal/the-architecture-of-disappearing': typeof JournalTheArchitectureOfDisappearingRoute
  '/journal/what-the-river-has-taught-us-about-time': typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  '/rooms/family-room': typeof RoomsFamilyRoomRoute
  '/rooms/riverfront-deluxe': typeof RoomsRiverfrontDeluxeRoute
  '/rooms/standard-river': typeof RoomsStandardRiverRoute
  '/journal/': typeof JournalIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/accommodations'
    | '/amenities-activities'
    | '/book'
    | '/booking-form'
    | '/contact'
    | '/dining'
    | '/dining-leisure'
    | '/experiences'
    | '/journal'
    | '/lodge'
    | '/plan'
    | '/pricing'
    | '/rooms'
    | '/suites'
    | '/terms'
    | '/vote'
    | '/journal/a-morning-with-the-beekeepers-of-gomba'
    | '/journal/building-with-the-community'
    | '/journal/discovering-arusha-through-nature-and-authentic-hospitality'
    | '/journal/life-along-the-nduruma-river'
    | '/journal/perfect-arusha-stay-for-safari-travelers-2026'
    | '/journal/reading-the-sky-over-mount-meru'
    | '/journal/the-architecture-of-disappearing'
    | '/journal/what-the-river-has-taught-us-about-time'
    | '/rooms/family-room'
    | '/rooms/riverfront-deluxe'
    | '/rooms/standard-river'
    | '/journal/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/accommodations'
    | '/amenities-activities'
    | '/book'
    | '/booking-form'
    | '/contact'
    | '/dining'
    | '/dining-leisure'
    | '/experiences'
    | '/lodge'
    | '/plan'
    | '/pricing'
    | '/suites'
    | '/terms'
    | '/vote'
    | '/journal/a-morning-with-the-beekeepers-of-gomba'
    | '/journal/building-with-the-community'
    | '/journal/discovering-arusha-through-nature-and-authentic-hospitality'
    | '/journal/life-along-the-nduruma-river'
    | '/journal/perfect-arusha-stay-for-safari-travelers-2026'
    | '/journal/reading-the-sky-over-mount-meru'
    | '/journal/the-architecture-of-disappearing'
    | '/journal/what-the-river-has-taught-us-about-time'
    | '/rooms/family-room'
    | '/rooms/riverfront-deluxe'
    | '/rooms/standard-river'
    | '/journal'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/accommodations'
    | '/amenities-activities'
    | '/book'
    | '/booking-form'
    | '/contact'
    | '/dining'
    | '/dining-leisure'
    | '/experiences'
    | '/journal'
    | '/lodge'
    | '/plan'
    | '/pricing'
    | '/rooms'
    | '/suites'
    | '/terms'
    | '/vote'
    | '/journal/a-morning-with-the-beekeepers-of-gomba'
    | '/journal/building-with-the-community'
    | '/journal/discovering-arusha-through-nature-and-authentic-hospitality'
    | '/journal/life-along-the-nduruma-river'
    | '/journal/perfect-arusha-stay-for-safari-travelers-2026'
    | '/journal/reading-the-sky-over-mount-meru'
    | '/journal/the-architecture-of-disappearing'
    | '/journal/what-the-river-has-taught-us-about-time'
    | '/rooms/family-room'
    | '/rooms/riverfront-deluxe'
    | '/rooms/standard-river'
    | '/journal/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccommodationsRoute: typeof AccommodationsRoute
  AmenitiesActivitiesRoute: typeof AmenitiesActivitiesRoute
  BookRoute: typeof BookRoute
  BookingFormRoute: typeof BookingFormRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  DiningLeisureRoute: typeof DiningLeisureRoute
  ExperiencesRoute: typeof ExperiencesRoute
  JournalRoute: typeof JournalRouteWithChildren
  LodgeRoute: typeof LodgeRoute
  PlanRoute: typeof PlanRoute
  PricingRoute: typeof PricingRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SuitesRoute: typeof SuitesRoute
  TermsRoute: typeof TermsRoute
  VoteRoute: typeof VoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lodge': {
      id: '/lodge'
      path: '/lodge'
      fullPath: '/lodge'
      preLoaderRoute: typeof LodgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining-leisure': {
      id: '/dining-leisure'
      path: '/dining-leisure'
      fullPath: '/dining-leisure'
      preLoaderRoute: typeof DiningLeisureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-form': {
      id: '/booking-form'
      path: '/booking-form'
      fullPath: '/booking-form'
      preLoaderRoute: typeof BookingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities-activities': {
      id: '/amenities-activities'
      path: '/amenities-activities'
      fullPath: '/amenities-activities'
      preLoaderRoute: typeof AmenitiesActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations': {
      id: '/accommodations'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AccommodationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/rooms/standard-river': {
      id: '/rooms/standard-river'
      path: '/standard-river'
      fullPath: '/rooms/standard-river'
      preLoaderRoute: typeof RoomsStandardRiverRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/riverfront-deluxe': {
      id: '/rooms/riverfront-deluxe'
      path: '/riverfront-deluxe'
      fullPath: '/rooms/riverfront-deluxe'
      preLoaderRoute: typeof RoomsRiverfrontDeluxeRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/family-room': {
      id: '/rooms/family-room'
      path: '/family-room'
      fullPath: '/rooms/family-room'
      preLoaderRoute: typeof RoomsFamilyRoomRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/journal/what-the-river-has-taught-us-about-time': {
      id: '/journal/what-the-river-has-taught-us-about-time'
      path: '/what-the-river-has-taught-us-about-time'
      fullPath: '/journal/what-the-river-has-taught-us-about-time'
      preLoaderRoute: typeof JournalWhatTheRiverHasTaughtUsAboutTimeRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/the-architecture-of-disappearing': {
      id: '/journal/the-architecture-of-disappearing'
      path: '/the-architecture-of-disappearing'
      fullPath: '/journal/the-architecture-of-disappearing'
      preLoaderRoute: typeof JournalTheArchitectureOfDisappearingRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/reading-the-sky-over-mount-meru': {
      id: '/journal/reading-the-sky-over-mount-meru'
      path: '/reading-the-sky-over-mount-meru'
      fullPath: '/journal/reading-the-sky-over-mount-meru'
      preLoaderRoute: typeof JournalReadingTheSkyOverMountMeruRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/perfect-arusha-stay-for-safari-travelers-2026': {
      id: '/journal/perfect-arusha-stay-for-safari-travelers-2026'
      path: '/perfect-arusha-stay-for-safari-travelers-2026'
      fullPath: '/journal/perfect-arusha-stay-for-safari-travelers-2026'
      preLoaderRoute: typeof JournalPerfectArushaStayForSafariTravelers2026RouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/life-along-the-nduruma-river': {
      id: '/journal/life-along-the-nduruma-river'
      path: '/life-along-the-nduruma-river'
      fullPath: '/journal/life-along-the-nduruma-river'
      preLoaderRoute: typeof JournalLifeAlongTheNdurumaRiverRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/discovering-arusha-through-nature-and-authentic-hospitality': {
      id: '/journal/discovering-arusha-through-nature-and-authentic-hospitality'
      path: '/discovering-arusha-through-nature-and-authentic-hospitality'
      fullPath: '/journal/discovering-arusha-through-nature-and-authentic-hospitality'
      preLoaderRoute: typeof JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/building-with-the-community': {
      id: '/journal/building-with-the-community'
      path: '/building-with-the-community'
      fullPath: '/journal/building-with-the-community'
      preLoaderRoute: typeof JournalBuildingWithTheCommunityRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/a-morning-with-the-beekeepers-of-gomba': {
      id: '/journal/a-morning-with-the-beekeepers-of-gomba'
      path: '/a-morning-with-the-beekeepers-of-gomba'
      fullPath: '/journal/a-morning-with-the-beekeepers-of-gomba'
      preLoaderRoute: typeof JournalAMorningWithTheBeekeepersOfGombaRouteImport
      parentRoute: typeof JournalRoute
    }
  }
}

interface JournalRouteChildren {
  JournalAMorningWithTheBeekeepersOfGombaRoute: typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  JournalBuildingWithTheCommunityRoute: typeof JournalBuildingWithTheCommunityRoute
  JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute: typeof JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute
  JournalLifeAlongTheNdurumaRiverRoute: typeof JournalLifeAlongTheNdurumaRiverRoute
  JournalPerfectArushaStayForSafariTravelers2026Route: typeof JournalPerfectArushaStayForSafariTravelers2026Route
  JournalReadingTheSkyOverMountMeruRoute: typeof JournalReadingTheSkyOverMountMeruRoute
  JournalTheArchitectureOfDisappearingRoute: typeof JournalTheArchitectureOfDisappearingRoute
  JournalWhatTheRiverHasTaughtUsAboutTimeRoute: typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalAMorningWithTheBeekeepersOfGombaRoute:
    JournalAMorningWithTheBeekeepersOfGombaRoute,
  JournalBuildingWithTheCommunityRoute: JournalBuildingWithTheCommunityRoute,
  JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute:
    JournalDiscoveringArushaThroughNatureAndAuthenticHospitalityRoute,
  JournalLifeAlongTheNdurumaRiverRoute: JournalLifeAlongTheNdurumaRiverRoute,
  JournalPerfectArushaStayForSafariTravelers2026Route:
    JournalPerfectArushaStayForSafariTravelers2026Route,
  JournalReadingTheSkyOverMountMeruRoute:
    JournalReadingTheSkyOverMountMeruRoute,
  JournalTheArchitectureOfDisappearingRoute:
    JournalTheArchitectureOfDisappearingRoute,
  JournalWhatTheRiverHasTaughtUsAboutTimeRoute:
    JournalWhatTheRiverHasTaughtUsAboutTimeRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface RoomsRouteChildren {
  RoomsFamilyRoomRoute: typeof RoomsFamilyRoomRoute
  RoomsRiverfrontDeluxeRoute: typeof RoomsRiverfrontDeluxeRoute
  RoomsStandardRiverRoute: typeof RoomsStandardRiverRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsFamilyRoomRoute: RoomsFamilyRoomRoute,
  RoomsRiverfrontDeluxeRoute: RoomsRiverfrontDeluxeRoute,
  RoomsStandardRiverRoute: RoomsStandardRiverRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccommodationsRoute: AccommodationsRoute,
  AmenitiesActivitiesRoute: AmenitiesActivitiesRoute,
  BookRoute: BookRoute,
  BookingFormRoute: BookingFormRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  DiningLeisureRoute: DiningLeisureRoute,
  ExperiencesRoute: ExperiencesRoute,
  JournalRoute: JournalRouteWithChildren,
  LodgeRoute: LodgeRoute,
  PlanRoute: PlanRoute,
  PricingRoute: PricingRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SuitesRoute: SuitesRoute,
  TermsRoute: TermsRoute,
  VoteRoute: VoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
