/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LodgeRouteImport } from './routes/lodge'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as RoomsStandardRiverRouteImport } from './routes/rooms.standard-river'
import { Route as RoomsRiverfrontDeluxeRouteImport } from './routes/rooms.riverfront-deluxe'
import { Route as RoomsFamilyRoomRouteImport } from './routes/rooms.family-room'
import { Route as JournalWildGingerBaobabRosehipRouteImport } from './routes/journal.wild-ginger-baobab-rosehip'
import { Route as JournalWhatTheRiverHasTaughtUsAboutTimeRouteImport } from './routes/journal.what-the-river-has-taught-us-about-time'
import { Route as JournalTheArchitectureOfDisappearingRouteImport } from './routes/journal.the-architecture-of-disappearing'
import { Route as JournalReadingTheSkyOverMountMeruRouteImport } from './routes/journal.reading-the-sky-over-mount-meru'
import { Route as JournalAMorningWithTheBeekeepersOfGombaRouteImport } from './routes/journal.a-morning-with-the-beekeepers-of-gomba'

const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LodgeRoute = LodgeRouteImport.update({
  id: '/lodge',
  path: '/lodge',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const RoomsStandardRiverRoute = RoomsStandardRiverRouteImport.update({
  id: '/standard-river',
  path: '/standard-river',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsRiverfrontDeluxeRoute = RoomsRiverfrontDeluxeRouteImport.update({
  id: '/riverfront-deluxe',
  path: '/riverfront-deluxe',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsFamilyRoomRoute = RoomsFamilyRoomRouteImport.update({
  id: '/family-room',
  path: '/family-room',
  getParentRoute: () => RoomsRoute,
} as any)
const JournalWildGingerBaobabRosehipRoute =
  JournalWildGingerBaobabRosehipRouteImport.update({
    id: '/wild-ginger-baobab-rosehip',
    path: '/wild-ginger-baobab-rosehip',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalWhatTheRiverHasTaughtUsAboutTimeRoute =
  JournalWhatTheRiverHasTaughtUsAboutTimeRouteImport.update({
    id: '/what-the-river-has-taught-us-about-time',
    path: '/what-the-river-has-taught-us-about-time',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalTheArchitectureOfDisappearingRoute =
  JournalTheArchitectureOfDisappearingRouteImport.update({
    id: '/the-architecture-of-disappearing',
    path: '/the-architecture-of-disappearing',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalReadingTheSkyOverMountMeruRoute =
  JournalReadingTheSkyOverMountMeruRouteImport.update({
    id: '/reading-the-sky-over-mount-meru',
    path: '/reading-the-sky-over-mount-meru',
    getParentRoute: () => JournalRoute,
  } as any)
const JournalAMorningWithTheBeekeepersOfGombaRoute =
  JournalAMorningWithTheBeekeepersOfGombaRouteImport.update({
    id: '/a-morning-with-the-beekeepers-of-gomba',
    path: '/a-morning-with-the-beekeepers-of-gomba',
    getParentRoute: () => JournalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/journal': typeof JournalRouteWithChildren
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/suites': typeof SuitesRoute
  '/journal/a-morning-with-the-beekeepers-of-gomba': typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  '/journal/reading-the-sky-over-mount-meru': typeof JournalReadingTheSkyOverMountMeruRoute
  '/journal/the-architecture-of-disappearing': typeof JournalTheArchitectureOfDisappearingRoute
  '/journal/what-the-river-has-taught-us-about-time': typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  '/journal/wild-ginger-baobab-rosehip': typeof JournalWildGingerBaobabRosehipRoute
  '/rooms/family-room': typeof RoomsFamilyRoomRoute
  '/rooms/riverfront-deluxe': typeof RoomsRiverfrontDeluxeRoute
  '/rooms/standard-river': typeof RoomsStandardRiverRoute
  '/journal/': typeof JournalIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/suites': typeof SuitesRoute
  '/journal/a-morning-with-the-beekeepers-of-gomba': typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  '/journal/reading-the-sky-over-mount-meru': typeof JournalReadingTheSkyOverMountMeruRoute
  '/journal/the-architecture-of-disappearing': typeof JournalTheArchitectureOfDisappearingRoute
  '/journal/what-the-river-has-taught-us-about-time': typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  '/journal/wild-ginger-baobab-rosehip': typeof JournalWildGingerBaobabRosehipRoute
  '/rooms/family-room': typeof RoomsFamilyRoomRoute
  '/rooms/riverfront-deluxe': typeof RoomsRiverfrontDeluxeRoute
  '/rooms/standard-river': typeof RoomsStandardRiverRoute
  '/journal': typeof JournalIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/journal': typeof JournalRouteWithChildren
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/suites': typeof SuitesRoute
  '/journal/a-morning-with-the-beekeepers-of-gomba': typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  '/journal/reading-the-sky-over-mount-meru': typeof JournalReadingTheSkyOverMountMeruRoute
  '/journal/the-architecture-of-disappearing': typeof JournalTheArchitectureOfDisappearingRoute
  '/journal/what-the-river-has-taught-us-about-time': typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  '/journal/wild-ginger-baobab-rosehip': typeof JournalWildGingerBaobabRosehipRoute
  '/rooms/family-room': typeof RoomsFamilyRoomRoute
  '/rooms/riverfront-deluxe': typeof RoomsRiverfrontDeluxeRoute
  '/rooms/standard-river': typeof RoomsStandardRiverRoute
  '/journal/': typeof JournalIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/dining'
    | '/experiences'
    | '/journal'
    | '/lodge'
    | '/plan'
    | '/rooms'
    | '/suites'
    | '/journal/a-morning-with-the-beekeepers-of-gomba'
    | '/journal/reading-the-sky-over-mount-meru'
    | '/journal/the-architecture-of-disappearing'
    | '/journal/what-the-river-has-taught-us-about-time'
    | '/journal/wild-ginger-baobab-rosehip'
    | '/rooms/family-room'
    | '/rooms/riverfront-deluxe'
    | '/rooms/standard-river'
    | '/journal/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/dining'
    | '/experiences'
    | '/lodge'
    | '/plan'
    | '/suites'
    | '/journal/a-morning-with-the-beekeepers-of-gomba'
    | '/journal/reading-the-sky-over-mount-meru'
    | '/journal/the-architecture-of-disappearing'
    | '/journal/what-the-river-has-taught-us-about-time'
    | '/journal/wild-ginger-baobab-rosehip'
    | '/rooms/family-room'
    | '/rooms/riverfront-deluxe'
    | '/rooms/standard-river'
    | '/journal'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/dining'
    | '/experiences'
    | '/journal'
    | '/lodge'
    | '/plan'
    | '/rooms'
    | '/suites'
    | '/journal/a-morning-with-the-beekeepers-of-gomba'
    | '/journal/reading-the-sky-over-mount-meru'
    | '/journal/the-architecture-of-disappearing'
    | '/journal/what-the-river-has-taught-us-about-time'
    | '/journal/wild-ginger-baobab-rosehip'
    | '/rooms/family-room'
    | '/rooms/riverfront-deluxe'
    | '/rooms/standard-river'
    | '/journal/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  DiningRoute: typeof DiningRoute
  ExperiencesRoute: typeof ExperiencesRoute
  JournalRoute: typeof JournalRouteWithChildren
  LodgeRoute: typeof LodgeRoute
  PlanRoute: typeof PlanRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SuitesRoute: typeof SuitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lodge': {
      id: '/lodge'
      path: '/lodge'
      fullPath: '/lodge'
      preLoaderRoute: typeof LodgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/rooms/standard-river': {
      id: '/rooms/standard-river'
      path: '/standard-river'
      fullPath: '/rooms/standard-river'
      preLoaderRoute: typeof RoomsStandardRiverRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/riverfront-deluxe': {
      id: '/rooms/riverfront-deluxe'
      path: '/riverfront-deluxe'
      fullPath: '/rooms/riverfront-deluxe'
      preLoaderRoute: typeof RoomsRiverfrontDeluxeRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/family-room': {
      id: '/rooms/family-room'
      path: '/family-room'
      fullPath: '/rooms/family-room'
      preLoaderRoute: typeof RoomsFamilyRoomRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/journal/wild-ginger-baobab-rosehip': {
      id: '/journal/wild-ginger-baobab-rosehip'
      path: '/wild-ginger-baobab-rosehip'
      fullPath: '/journal/wild-ginger-baobab-rosehip'
      preLoaderRoute: typeof JournalWildGingerBaobabRosehipRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/what-the-river-has-taught-us-about-time': {
      id: '/journal/what-the-river-has-taught-us-about-time'
      path: '/what-the-river-has-taught-us-about-time'
      fullPath: '/journal/what-the-river-has-taught-us-about-time'
      preLoaderRoute: typeof JournalWhatTheRiverHasTaughtUsAboutTimeRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/the-architecture-of-disappearing': {
      id: '/journal/the-architecture-of-disappearing'
      path: '/the-architecture-of-disappearing'
      fullPath: '/journal/the-architecture-of-disappearing'
      preLoaderRoute: typeof JournalTheArchitectureOfDisappearingRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/reading-the-sky-over-mount-meru': {
      id: '/journal/reading-the-sky-over-mount-meru'
      path: '/reading-the-sky-over-mount-meru'
      fullPath: '/journal/reading-the-sky-over-mount-meru'
      preLoaderRoute: typeof JournalReadingTheSkyOverMountMeruRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/a-morning-with-the-beekeepers-of-gomba': {
      id: '/journal/a-morning-with-the-beekeepers-of-gomba'
      path: '/a-morning-with-the-beekeepers-of-gomba'
      fullPath: '/journal/a-morning-with-the-beekeepers-of-gomba'
      preLoaderRoute: typeof JournalAMorningWithTheBeekeepersOfGombaRouteImport
      parentRoute: typeof JournalRoute
    }
  }
}

interface JournalRouteChildren {
  JournalAMorningWithTheBeekeepersOfGombaRoute: typeof JournalAMorningWithTheBeekeepersOfGombaRoute
  JournalReadingTheSkyOverMountMeruRoute: typeof JournalReadingTheSkyOverMountMeruRoute
  JournalTheArchitectureOfDisappearingRoute: typeof JournalTheArchitectureOfDisappearingRoute
  JournalWhatTheRiverHasTaughtUsAboutTimeRoute: typeof JournalWhatTheRiverHasTaughtUsAboutTimeRoute
  JournalWildGingerBaobabRosehipRoute: typeof JournalWildGingerBaobabRosehipRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalAMorningWithTheBeekeepersOfGombaRoute:
    JournalAMorningWithTheBeekeepersOfGombaRoute,
  JournalReadingTheSkyOverMountMeruRoute:
    JournalReadingTheSkyOverMountMeruRoute,
  JournalTheArchitectureOfDisappearingRoute:
    JournalTheArchitectureOfDisappearingRoute,
  JournalWhatTheRiverHasTaughtUsAboutTimeRoute:
    JournalWhatTheRiverHasTaughtUsAboutTimeRoute,
  JournalWildGingerBaobabRosehipRoute: JournalWildGingerBaobabRosehipRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface RoomsRouteChildren {
  RoomsFamilyRoomRoute: typeof RoomsFamilyRoomRoute
  RoomsRiverfrontDeluxeRoute: typeof RoomsRiverfrontDeluxeRoute
  RoomsStandardRiverRoute: typeof RoomsStandardRiverRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsFamilyRoomRoute: RoomsFamilyRoomRoute,
  RoomsRiverfrontDeluxeRoute: RoomsRiverfrontDeluxeRoute,
  RoomsStandardRiverRoute: RoomsStandardRiverRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  DiningRoute: DiningRoute,
  ExperiencesRoute: ExperiencesRoute,
  JournalRoute: JournalRouteWithChildren,
  LodgeRoute: LodgeRoute,
  PlanRoute: PlanRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SuitesRoute: SuitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
