/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LodgeRouteImport } from './routes/lodge'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuitesIndexRouteImport } from './routes/suites.index'
import { Route as SuitesStandardRiverRouteImport } from './routes/suites.standard-river'
import { Route as SuitesRiverfrontDeluxeRouteImport } from './routes/suites.riverfront-deluxe'
import { Route as SuitesFamilySuiteRouteImport } from './routes/suites.family-suite'

const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LodgeRoute = LodgeRouteImport.update({
  id: '/lodge',
  path: '/lodge',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesIndexRoute = SuitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuitesRoute,
} as any)
const SuitesStandardRiverRoute = SuitesStandardRiverRouteImport.update({
  id: '/standard-river',
  path: '/standard-river',
  getParentRoute: () => SuitesRoute,
} as any)
const SuitesRiverfrontDeluxeRoute = SuitesRiverfrontDeluxeRouteImport.update({
  id: '/riverfront-deluxe',
  path: '/riverfront-deluxe',
  getParentRoute: () => SuitesRoute,
} as any)
const SuitesFamilySuiteRoute = SuitesFamilySuiteRouteImport.update({
  id: '/family-suite',
  path: '/family-suite',
  getParentRoute: () => SuitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/journal': typeof JournalRoute
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/suites': typeof SuitesRouteWithChildren
  '/suites/family-suite': typeof SuitesFamilySuiteRoute
  '/suites/riverfront-deluxe': typeof SuitesRiverfrontDeluxeRoute
  '/suites/standard-river': typeof SuitesStandardRiverRoute
  '/suites/': typeof SuitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/journal': typeof JournalRoute
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/suites/family-suite': typeof SuitesFamilySuiteRoute
  '/suites/riverfront-deluxe': typeof SuitesRiverfrontDeluxeRoute
  '/suites/standard-river': typeof SuitesStandardRiverRoute
  '/suites': typeof SuitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dining': typeof DiningRoute
  '/experiences': typeof ExperiencesRoute
  '/journal': typeof JournalRoute
  '/lodge': typeof LodgeRoute
  '/plan': typeof PlanRoute
  '/suites': typeof SuitesRouteWithChildren
  '/suites/family-suite': typeof SuitesFamilySuiteRoute
  '/suites/riverfront-deluxe': typeof SuitesRiverfrontDeluxeRoute
  '/suites/standard-river': typeof SuitesStandardRiverRoute
  '/suites/': typeof SuitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dining'
    | '/experiences'
    | '/journal'
    | '/lodge'
    | '/plan'
    | '/suites'
    | '/suites/family-suite'
    | '/suites/riverfront-deluxe'
    | '/suites/standard-river'
    | '/suites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dining'
    | '/experiences'
    | '/journal'
    | '/lodge'
    | '/plan'
    | '/suites/family-suite'
    | '/suites/riverfront-deluxe'
    | '/suites/standard-river'
    | '/suites'
  id:
    | '__root__'
    | '/'
    | '/dining'
    | '/experiences'
    | '/journal'
    | '/lodge'
    | '/plan'
    | '/suites'
    | '/suites/family-suite'
    | '/suites/riverfront-deluxe'
    | '/suites/standard-river'
    | '/suites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiningRoute: typeof DiningRoute
  ExperiencesRoute: typeof ExperiencesRoute
  JournalRoute: typeof JournalRoute
  LodgeRoute: typeof LodgeRoute
  PlanRoute: typeof PlanRoute
  SuitesRoute: typeof SuitesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lodge': {
      id: '/lodge'
      path: '/lodge'
      fullPath: '/lodge'
      preLoaderRoute: typeof LodgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites/': {
      id: '/suites/'
      path: '/'
      fullPath: '/suites/'
      preLoaderRoute: typeof SuitesIndexRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/suites/standard-river': {
      id: '/suites/standard-river'
      path: '/standard-river'
      fullPath: '/suites/standard-river'
      preLoaderRoute: typeof SuitesStandardRiverRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/suites/riverfront-deluxe': {
      id: '/suites/riverfront-deluxe'
      path: '/riverfront-deluxe'
      fullPath: '/suites/riverfront-deluxe'
      preLoaderRoute: typeof SuitesRiverfrontDeluxeRouteImport
      parentRoute: typeof SuitesRoute
    }
    '/suites/family-suite': {
      id: '/suites/family-suite'
      path: '/family-suite'
      fullPath: '/suites/family-suite'
      preLoaderRoute: typeof SuitesFamilySuiteRouteImport
      parentRoute: typeof SuitesRoute
    }
  }
}

interface SuitesRouteChildren {
  SuitesFamilySuiteRoute: typeof SuitesFamilySuiteRoute
  SuitesRiverfrontDeluxeRoute: typeof SuitesRiverfrontDeluxeRoute
  SuitesStandardRiverRoute: typeof SuitesStandardRiverRoute
  SuitesIndexRoute: typeof SuitesIndexRoute
}

const SuitesRouteChildren: SuitesRouteChildren = {
  SuitesFamilySuiteRoute: SuitesFamilySuiteRoute,
  SuitesRiverfrontDeluxeRoute: SuitesRiverfrontDeluxeRoute,
  SuitesStandardRiverRoute: SuitesStandardRiverRoute,
  SuitesIndexRoute: SuitesIndexRoute,
}

const SuitesRouteWithChildren =
  SuitesRoute._addFileChildren(SuitesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiningRoute: DiningRoute,
  ExperiencesRoute: ExperiencesRoute,
  JournalRoute: JournalRoute,
  LodgeRoute: LodgeRoute,
  PlanRoute: PlanRoute,
  SuitesRoute: SuitesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
